### ISSUE TITLE
Google Actions: Webhook handler does not include name

### ISSUE THREAD

**Issue by asarazan** [jovotech/jovo-model#18]
If I attempt to deploy using `gactions push`, I get the following error:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Event handler contains function call named 'Jovo' which is not present in the interaction model."
          }
        ]
      }
    ]
  }
}
```

The problem resolves by fixing the webhook file by adding the first two lines of the following snippet:
```yaml
handlers:
- name: Jovo
httpsEndpoint:
  baseUrl: <some_url>
  endpointApiVersion: 2

```
